export interface Department {
  [key: string]: string;
}

export const departments: Department = {
  "amazonas": "ama",
  "antioquia": "ant",
  "arauca": "ara",
  "atlantico": "atl",
  "atlántico": "atl",
  "bolivar": "bol",
  "bolívar": "bol",
  "boyaca": "boy",
  "boyacá": "boy",
  "caldas": "cal",
  "caqueta": "caq",
  "caquetá": "caq",
  "casanare": "cas",
  "cauca": "cau",
  "cesar": "ces",
  "choco": "cho",
  "chocó": "cho",
  "cundinamarca": "cun",
  "cordoba": "cor",
  "córdoba": "cor",
  "guainia": "gua",
  "guainía": "gua",
  "guaviare": "guv",
  "huila": "hui",
  "la guajira": "lag",
  "guajira": "lag",
  "magdalena": "mag",
  "meta": "met",
  "nariño": "nar",
  "norte de santander": "nsa",
  "putumayo": "put",
  "quindio": "qui",
  "quindío": "qui",
  "risaralda": "ris",
  "san andres": "sap",
  "san andrés": "sap",
  "santander": "san",
  "sucre": "suc",
  "tolima": "tol",
  "valle del cauca": "vac",
  "vaupes": "vau",
  "vaupés": "vau",
  "vichada": "vid"
};

export const rightNames: Department = {
  ama: 'Amazonas',
  ant: 'Antioquia',
  ara: 'Arauca', 
  atl: 'Atlántico', 
  bol: 'Bolívar', 
  boy: 'Boyacá', 
  cal: 'Caldas', 
  caq: 'Caquetá', 
  cas: 'Casanare', 
  cau: 'Cauca', 
  ces: 'Cesar', 
  cho: 'Chocó', 
  cun: 'Cundinamarca', 
  cor: 'Córdoba', 
  gua: 'Guainía', 
  guv: 'Guaviare', 
  hui: 'Huila', 
  lag: 'La guajira', 
  mag: 'Magdalena', 
  met: 'Meta', 
  nar: 'Nariño', 
  nsa: 'Norte de santander', 
  put: 'Putumayo', 
  qui: 'Quindío', 
  ris: 'Risaralda', 
  sap: 'San Andrés y Providencia', 
  san: 'Santander', 
  suc: 'Sucre',
  tol: 'Tolima',
  vac: 'Valle del cauca',
  vau: 'Vaupés',
  vid: 'Vichada'
};