export interface State {
  [key: string]: string;
}

export const states: State = {
  "aguascalientes": "AGS",
  "baja california": "BC",
  "baja california sur": "BCS",
  "campeche": "CAM",
  "chiapas": "CHIS",
  "chihuahua": "CHIH",
  "coahuila": "COAH",
  "colima": "COL",
  "durango": "DGO",
  "estado de méxico": "MEX",
  "estado de mexico": "MEX",
  "méxico": "MEX",
  "mexico": "MEX",
  "guanajuato": "GTO",
  "guerrero": "GRO",
  "hidalgo": "HGO",
  "jalisco": "JAL",
  "michoacán": "MICH",
  "michoacan": "MICH",
  "morelos": "MOR",
  "nayarit": "NAY",
  "nuevo león": "NL",
  "nuevo leon": "NL",
  "oaxaca": "OAX",
  "puebla": "PUE",
  "querétaro": "QRO",
  "queretaro": "QRO",
  "quintana roo": "QROO",
  "san luis potosí": "SLP",
  "san luis potosi": "SLP",
  "sinaloa": "SIN",
  "sonora": "SON",
  "tabasco": "TAB",
  "tamaulipas": "TAMPS",
  "tlaxcala": "TLAX",
  "veracruz": "VER",
  "yucatán": "YUC",
  "yucatan": "YUC",
  "zacatecas": "ZAC",
};

export const rightNames: State = {
  "AGS": "Aguascalientes",
  "BC": "Baja California",
  "BCS": "Baja California Sur",
  "CAM": "Campeche",
  "CHIS": "Chiapas",
  "CHIH": "Chihuahua",
  "COAH": "Coahuila",
  "COL": "Colima",
  "DGO": "Durango",
  "MEX": "Estado de México",
  "GTO": "Guanajuato",
  "GRO": "Guerrero",
  "HGO": "Hidalgo",
  "JAL": "Jalisco",
  "MICH": "Michoacán",
  "MOR": "Morelos",
  "NAY": "Nayarit",
  "NL": "Nuevo León",
  "OAX": "Oaxaca",
  "PUE": "Puebla",
  "QRO": "Querétaro",
  "QROO": "Quintana Roo",
  "SLP": "San Luis Potosí",
  "SIN": "Sinaloa",
  "SON": "Sonora",
  "TAB": "Tabasco",
  "TAMPS": "Tamaulipas",
  "TLAX": "Tlaxcala",
  "VER": "Veracruz",
  "YUC": "Yucatán",
  "ZAC": "Zacatecas",
};