export interface Region {
  [key: string]: string;
}

export const regions: Region = {
  "bretagne": "bre",
  "pays de la loire": "pay",
  "nouvelle-aquitaine": "nou",
  "occitanie": "occ",
  "provence-alpes-côte d'azur": "pro",
  "provence-alpes-cote d'azur": "pro",
  "provence alpes côte d'azur": "pro",
  "provence alpes cote d'azur": "pro",
  "auvergne-rhône-alpes": "auv",
  "auvergne-rhone-alpes": "auv",
  "auvergne rhône alpes": "auv",
  "auvergne rhone alpes": "auv",
  "bourgogne-franche-comté": "bou",
  "bourgogne-franche-comte": "bou",
  "bourgogne franche comté": "bou",
  "bourgogne franche comte": "bou",
  "grand est": "gra",
  "centre-val de loire": "cen",
  "centre val de loire": "cen",
  "île-de-france": "ile",
  "ile-de-france": "ile",
  "île de france": "ile",
  "ile de france": "ile",
  "normandie": "nor",
  "hauts-de-france": "hau",
  "hauts de france": "hau",
  "guyane": "guy",
  "guadeloupe": "gua",
  "mayotte": "may",
  "la réunion": "lar",
  "la reunion": "lar",
  "corse": "cor",
  "martinique": "mar"
};

export const rightNames: Region = {
  "bre": "Bretagne",
  "pay": "Pays de la Loire",
  "nou": "Nouvelle-Aquitaine",
  "occ": "Occitanie",
  "pro": "Provence-Alpes-Côte d'Azur",
  "auv": "Auvergne-Rhône-Alpes",
  "bou": "Bourgogne-Franche-Comté",
  "gra": "Grand Est",
  "cen": "Centre-Val de Loire",
  "ile": "Île-de-France",
  "nor": "Normandie",
  "hau": "Hauts-de-France",
  "guy": "Guyane",
  "gua": "Guadeloupe",
  "may": "Mayotte",
  "lar": "La Réunion",
  "cor": "Corse",
  "mar": "Martinique"
};